// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAs-ug581XaSfPAtSLFlFU61oimjM4S8k',
    appId: '1:377608618654:web:f85ed26d087423ef05718f',
    messagingSenderId: '377608618654',
    projectId: 'tictactoe-47e15',
    authDomain: 'tictactoe-47e15.firebaseapp.com',
    storageBucket: 'tictactoe-47e15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZK6-1rg9jwS13eQy7w6oQSuzGcNjQ_FE',
    appId: '1:377608618654:android:20d8954cc34fc3c405718f',
    messagingSenderId: '377608618654',
    projectId: 'tictactoe-47e15',
    storageBucket: 'tictactoe-47e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUmdC1gxoJvwKRVskgdHWQ12YnfrXtMa4',
    appId: '1:377608618654:ios:c9a0f84ae8fa28b805718f',
    messagingSenderId: '377608618654',
    projectId: 'tictactoe-47e15',
    storageBucket: 'tictactoe-47e15.appspot.com',
    iosBundleId: 'dev.ex3.tictactoe',
  );
}
